In [1]:
integer = 10
floating_point = 10.5
string1 = 'Hello Python'
string2 = "Hello Python!"

In [3]:
print(integer, type(integer))
print(floating_point, type(floating_point))
print(string1, type(string1))
print(string2, type(string2))

10 <class 'int'>
10.5 <class 'float'>
Hello Python <class 'str'>
Hello Python! <class 'str'>


In [1]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]

add_list = list_1 + list_2

print(add_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
twolist = [[1, 2], [3, 4], [5, 6]]

print(twolist[0][0])

1


In [3]:
poped = list_1.pop()
print(poped)
print(list_1)

5
[1, 2, 3, 4]


In [4]:
list_1.append(10)
print(list_1)

[1, 2, 3, 4, 10]


In [5]:
list_1[0] = 5
print(list_1)

[5, 2, 3, 4, 10]


In [6]:
tuple = (1, 2, 3, 4, 5)
tu_pop = tuple.pop()

print(tu_pop)

tuple.append(10)
print(tuple)

AttributeError: 'tuple' object has no attribute 'pop'

In [7]:
dict = {'key0':0, 'key1':1, 'key2':2, 'key3': 3}
print(dict)

{'key0': 0, 'key1': 1, 'key2': 2, 'key3': 3}


In [8]:
print(dict['key1'])

1


In [11]:
_list = [i+13 for i in range(10)]
print(_list)

[13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


In [10]:
_list_if = [i for i in range(10) if i%2 == 0]
print(_list_if)

[0, 2, 4, 6, 8]


In [12]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
def my_func(a, b, c, d, e):
    return a, b, c, d, e

In [15]:
out = my_func(1, 2, 3, 4, 5)
print(out)
print(out[0])

(1, 2, 3, 4, 5)
1


In [16]:
out1, out2, out3, out4, out5 = my_func(1, 2, 3, 4, 5)
print(out1, out2, out3)

1 2 3


In [18]:
out6, out7 = my_func(1, 2, 3, 4, 5)

ValueError: too many values to unpack (expected 2)

In [19]:
import tensorflow as tf

In [21]:
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
print(tensor)

Tensor("Const:0", shape=(3, 2), dtype=int32)


In [22]:
with tf.Session() as sess:
    _tensor = sess.run(tensor)
    print(_tensor)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
import tensorflow as tf

In [14]:
data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
p1 = tf.placeholder(tf.float32, shape=[None,5])

with tf.Session() as sess:
    _p1 = sess.run(p1, feed_dict={p1: data})
    print(_p1)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]]


In [6]:
value = [1, 3, 4, 5, 6]
var = tf.Variable(value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    _var = sess.run(var)
    print(_var)

[1 3 4 5 6]


In [1]:
import numpy as np

In [5]:
def one_hot_encode(x, n_classes):
    """
    One hot encode a list of sample labels. Return a one-hot encoded vector for each label.
    : x: List of sample Labels
    : return: Numpy array of one-hot encoded labels
     """
    return np.eye(n_classes)[x]

list = ["a","b","c","a","b","d","e","a","e"]
#list = [0,1,2,3,4,3,2,1,0]
n_classes = 5
one_hot_list = one_hot_encode(list, n_classes)
print(one_hot_list)
          

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [13]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

array = [0, 0, 0, 1, 0, 0]

index = 0
for i in range(0,len(array)):
    if array[i] == 1:
        print(i)



['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
['cold']
3
